version: '3'

services:
  fastapi:
    build: .
    container_name: hackaton_back
    networks:
      - hackaton_net
    ports:
      - '8001:80'
    environment:
      PORT: 80
      POSTGRES_HOST: postgres://admin:admin@hackaton_db/hackaton
    restart: always
  database:
    image: "postgres" # use latest official postgres version
    container_name: hackaton_db
    networks:
      - hackaton_net
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:

networks:
  hackaton_net:

volumes:
  database-data: # named volumes can be managed easier using docker-compose